// Danh sách ngân hàng với mã BIN
export const BANK_LIST = [
  { bin: '422589', name: 'Ngân hàng TNHH MTV CIMB Việt Nam (CIMB)' },
  { bin: '458761', name: 'Ngân hàng TNHH MTV HSBC (Việt Nam) (HSBC)' },
  { bin: '546034', name: 'Ngân hàng số CAKE by VPBank (CAKE)' },
  { bin: '546035', name: 'Ngân hàng số Ubank by VPBank (Ubank)' },
  { bin: '668888', name: 'Ngân hàng Đại chúng TNHH Kasikornbank (KBank)' },
  { bin: '796500', name: 'DBS Bank Ltd - Chi nhánh TP. Hồ Chí Minh (DBSBank)' },
  { bin: '801011', name: 'Ngân hàng Nonghyup - Chi nhánh Hà Nội (Nonghyup)' },
  { bin: '970400', name: 'Ngân hàng TMCP Sài Gòn Công Thương (SaigonBank)' },
  { bin: '970403', name: 'Ngân hàng TMCP Sài Gòn Thương Tín (Sacombank)' },
  { bin: '970405', name: 'Ngân hàng Nông nghiệp và Phát triển Nông thôn Việt Nam (Agribank)' },
  { bin: '970406', name: 'Ngân hàng TMCP Đông Á (DongABank)' },
  { bin: '970407', name: 'Ngân hàng TMCP Kỹ thương Việt Nam (Techcombank)' },
  { bin: '970408', name: 'Ngân hàng Thương mại TNHH MTV Dầu Khí Toàn Cầu (GPBank)' },
  { bin: '970409', name: 'Ngân hàng TMCP Bắc Á (BacABank)' },
  { bin: '970410', name: 'Ngân hàng Standard Chartered Việt Nam (Standard Chartered)' },
  { bin: '970412', name: 'Ngân hàng TMCP Đại Chúng Việt Nam (PVcomBank)' },
  { bin: '970414', name: 'Ngân hàng Thương mại TNHH MTV Đại Dương (Oceanbank)' },
  { bin: '970415', name: 'Ngân hàng TMCP Công thương Việt Nam (VietinBank)' },
  { bin: '970416', name: 'Ngân hàng TMCP Á Châu (ACB)' },
  { bin: '970418', name: 'Ngân hàng TMCP Đầu tư và Phát triển Việt Nam (BIDV)' },
  { bin: '970419', name: 'Ngân hàng TMCP Quốc Dân (NCB)' },
  { bin: '970421', name: 'Ngân hàng Liên doanh Việt - Nga (VRB)' },
  { bin: '970422', name: 'Ngân hàng TMCP Quân đội (MBBank)' },
  { bin: '970423', name: 'Ngân hàng TMCP Tiên Phong (TPBank)' },
  { bin: '970424', name: 'Ngân hàng TNHH MTV Shinhan Việt Nam (ShinhanBank)' },
  { bin: '970425', name: 'Ngân hàng TMCP An Bình (ABBANK)' },
  { bin: '970426', name: 'Ngân hàng TMCP Hàng Hải (MSB)' },
  { bin: '970427', name: 'Ngân hàng TMCP Việt Á (VietABank)' },
  { bin: '970428', name: 'Ngân hàng TMCP Nam Á (NamABank)' },
  { bin: '970429', name: 'Ngân hàng TMCP Sài Gòn (SCB)' },
  { bin: '970430', name: 'Ngân hàng TMCP Xăng dầu Petrolimex (PGBank)' },
  { bin: '970431', name: 'Ngân hàng TMCP Xuất Nhập khẩu Việt Nam (Eximbank)' },
  { bin: '970432', name: 'Ngân hàng TMCP Việt Nam Thịnh Vượng (VPBank)' },
  { bin: '970433', name: 'Ngân hàng TMCP Việt Nam Thương Tín (VietBank)' },
  { bin: '970434', name: 'Ngân hàng TNHH Indovina (IndovinaBank)' },
  { bin: '970436', name: 'Ngân hàng TMCP Ngoại Thương Việt Nam (Vietcombank)' },
  { bin: '970437', name: 'Ngân hàng TMCP PT Thành phố Hồ Chí Minh (HDBank)' },
  { bin: '970438', name: 'Ngân hàng TMCP Bảo Việt (BaoVietBank)' },
  { bin: '970439', name: 'Ngân hàng TNHH MTV Public Việt Nam (PublicBank)' },
  { bin: '970440', name: 'Ngân hàng TMCP Đông Nam Á (SeABank)' },
  { bin: '970441', name: 'Ngân hàng TMCP Quốc tế Việt Nam (VIB)' },
  { bin: '970442', name: 'Ngân hàng TNHH MTV Hong Leong Việt Nam (HongLeong)' },
  { bin: '970443', name: 'Ngân hàng TMCP Sài Gòn - Hà Nội (SHB)' },
  { bin: '970444', name: 'Ngân hàng TM TNHH MTV Xây dựng Việt Nam (CBBank)' },
  { bin: '970446', name: 'Ngân hàng Hợp tác xã Việt Nam (COOPBANK)' },
  { bin: '970448', name: 'Ngân hàng TMCP Phương Đông (OCB)' },
  { bin: '970449', name: 'Ngân hàng TMCP Bưu Điện Liên Việt (LienVietPostBank)' },
  { bin: '970452', name: 'Ngân hàng TMCP Kiên Long (KienLongBank)' },
  { bin: '970454', name: 'Ngân hàng TMCP Bản Việt (VietCapitalBank)' },
  { bin: '970455', name: 'Ngân hàng Công nghiệp Hàn Quốc - Chi nhánh Hà Nội (IBKHN)' },
  { bin: '970456', name: 'Ngân hàng Công nghiệp Hàn Quốc - Chi nhánh TP. Hồ Chí Minh (IBKHCM)' },
  { bin: '970457', name: 'Ngân hàng TNHH MTV Woori Việt Nam (Woori)' },
  { bin: '970458', name: 'Ngân hàng United Overseas - Chi nhánh TP. Hồ Chí Minh (United Overseas)' },
  { bin: '970462', name: 'Ngân hàng Kookmin - Chi nhánh Hà Nội (KookminHN)' },
  { bin: '970463', name: 'Ngân hàng Kookmin - Chi nhánh Tp. Hồ Chí Minh (KookminHCM)' }
];

export const getBankName = (bin: string): string => {
  return BANK_LIST.find((bank) => bank.bin === bin)?.name || bin;
};
