// Optimized VietQR Banks mapping - only commonly used banks
export const VIETQR_BANKS: Record<string, { shortName: string; name: string }> = {
  '970415': { shortName: 'VietinBank', name: 'Ngân hàng TMCP Công thương Việt Nam' },
  '970436': { shortName: 'Vietcombank', name: 'Ngân hàng TMCP Ngoại Thương Việt Nam' },
  '970418': { shortName: 'BIDV', name: 'Ngân hàng TMCP Đầu tư và Phát triển Việt Nam' },
  '970405': { shortName: 'Agribank', name: 'Ngân hàng Nông nghiệp và Phát triển Nông thôn Việt Nam' },
  '970448': { shortName: 'OCB', name: 'Ngân hàng TMCP Phương Đông' },
  '970422': { shortName: 'MBBank', name: 'Ngân hàng TMCP Quân đội' },
  '970407': { shortName: 'Techcombank', name: 'Ngân hàng TMCP Kỹ thương Việt Nam' },
  '970416': { shortName: 'ACB', name: 'Ngân hàng TMCP Á Châu' },
  '970432': { shortName: 'VPBank', name: 'Ngân hàng TMCP Việt Nam Thịnh Vượng' },
  '970423': { shortName: 'TPBank', name: 'Ngân hàng TMCP Tiên Phong' },
  '970403': { shortName: 'Sacombank', name: 'Ngân hàng TMCP Sài Gòn Thương Tín' },
  '970437': { shortName: 'HDBank', name: 'Ngân hàng TMCP Phát triển Thành phố Hồ Chí Minh' },
  '970454': { shortName: 'VietCapitalBank', name: 'Ngân hàng TMCP Bản Việt' },
  '970429': { shortName: 'SCB', name: 'Ngân hàng TMCP Sài Gòn' },
  '970441': { shortName: 'VIB', name: 'Ngân hàng TMCP Quốc tế Việt Nam' },
  '970443': { shortName: 'SHB', name: 'Ngân hàng TMCP Sài Gòn - Hà Nội' },
  '970431': { shortName: 'Eximbank', name: 'Ngân hàng TMCP Xuất Nhập khẩu Việt Nam' },
  '970426': { shortName: 'MSB', name: 'Ngân hàng TMCP Hàng Hải Việt Nam' },
  '546034': { shortName: 'CAKE', name: 'TMCP Việt Nam Thịnh Vượng - Ngân hàng số CAKE by VPBank' },
  '546035': { shortName: 'Ubank', name: 'TMCP Việt Nam Thịnh Vượng - Ngân hàng số Ubank by VPBank' },
  '971005': {
    shortName: 'ViettelMoney',
    name: 'Tổng Công ty Dịch vụ số Viettel - Chi nhánh tập đoàn công nghiệp viễn thông Quân Đội'
  },
  '963388': { shortName: 'Timo', name: 'Ngân hàng số Timo by Ban Viet Bank (Timo by Ban Viet Bank)' },
  '971011': { shortName: 'VNPTMoney', name: 'VNPT Money' },
  '970400': { shortName: 'SaigonBank', name: 'Ngân hàng TMCP Sài Gòn Công Thương' },
  '970409': { shortName: 'BacABank', name: 'Ngân hàng TMCP Bắc Á' },
  '971133': { shortName: 'PVcomBank Pay', name: 'Ngân hàng TMCP Đại Chúng Việt Nam Ngân hàng số' },
  '970412': { shortName: 'PVcomBank', name: 'Ngân hàng TMCP Đại Chúng Việt Nam' },
  '970414': { shortName: 'MBV', name: 'Ngân hàng TNHH MTV Việt Nam Hiện Đại' },
  '970419': { shortName: 'NCB', name: 'Ngân hàng TMCP Quốc Dân' },
  '970424': { shortName: 'ShinhanBank', name: 'Ngân hàng TNHH MTV Shinhan Việt Nam' },
  '970425': { shortName: 'ABBANK', name: 'Ngân hàng TMCP An Bình' },
  '970427': { shortName: 'VietABank', name: 'Ngân hàng TMCP Việt Á' },
  '970428': { shortName: 'NamABank', name: 'Ngân hàng TMCP Nam Á' },
  '970430': { shortName: 'PGBank', name: 'Ngân hàng TMCP Thịnh vượng và Phát triển' },
  '970433': { shortName: 'VietBank', name: 'Ngân hàng TMCP Việt Nam Thương Tín' },
  '970438': { shortName: 'BaoVietBank', name: 'Ngân hàng TMCP Bảo Việt' },
  '970440': { shortName: 'SeABank', name: 'Ngân hàng TMCP Đông Nam Á' },
  '970446': { shortName: 'COOPBANK', name: 'Ngân hàng Hợp tác xã Việt Nam' },
  '970449': { shortName: 'LPBank', name: 'Ngân hàng TMCP Lộc Phát Việt Nam' },
  '970452': { shortName: 'KienLongBank', name: 'Ngân hàng TMCP Kiên Long' },
  '668888': { shortName: 'KBank', name: 'Ngân hàng Đại chúng TNHH Kasikornbank' },
  '977777': { shortName: 'MAFC', name: 'Công ty Tài chính TNHH MTV Mirae Asset (Việt Nam) ' },
  '970467': { shortName: 'KEBHANAHN', name: 'Ngân hàng KEB Hana – Chi nhánh Hà Nội' },
  '970466': { shortName: 'KEBHanaHCM', name: 'Ngân hàng KEB Hana – Chi nhánh Thành phố Hồ Chí Minh' },
  '533948': { shortName: 'Citibank', name: 'Ngân hàng Citibank, N.A. - Chi nhánh Hà Nội' },
  '999888': { shortName: 'VBSP', name: 'Ngân hàng Chính sách Xã hội' },
  '970444': { shortName: 'CBBank', name: 'Ngân hàng Thương mại TNHH MTV Xây dựng Việt Nam' },
  '422589': { shortName: 'CIMB', name: 'Ngân hàng TNHH MTV CIMB Việt Nam' },
  '796500': { shortName: 'DBSBank', name: 'DBS Bank Ltd - Chi nhánh Thành phố Hồ Chí Minh' },
  '970406': { shortName: 'Vikki', name: 'Ngân hàng TNHH MTV Số Vikki' },
  '970439': { shortName: 'PublicBank', name: 'Ngân hàng TNHH MTV Public Việt Nam' },
  '970463': { shortName: 'KookminHCM', name: 'Ngân hàng Kookmin - Chi nhánh Thành phố Hồ Chí Minh' },
  '970462': { shortName: 'KookminHN', name: 'Ngân hàng Kookmin - Chi nhánh Hà Nội' },
  '970457': { shortName: 'Woori', name: 'Ngân hàng TNHH MTV Woori Việt Nam' },
  '970421': { shortName: 'VRB', name: 'Ngân hàng Liên doanh Việt - Nga' },
  '970408': { shortName: 'GPBank', name: 'Ngân hàng Thương mại TNHH MTV Dầu Khí Toàn Cầu' },
  '970442': { shortName: 'HongLeong', name: 'Ngân hàng TNHH MTV Hong Leong Việt Nam' },
  '458761': { shortName: 'HSBC', name: 'Ngân hàng TNHH MTV HSBC (Việt Nam)' },
  '970455': { shortName: 'IBKHN', name: 'Ngân hàng Công nghiệp Hàn Quốc - Chi nhánh Hà Nội' },
  '970456': { shortName: 'IBKHCM', name: 'Ngân hàng Công nghiệp Hàn Quốc - Chi nhánh TP. Hồ Chí Minh' },
  '801011': { shortName: 'Nonghyup', name: 'Ngân hàng Nonghyup - Chi nhánh Hà Nội' },
  '970458': { shortName: 'UnitedOverseas', name: 'Ngân hàng United Overseas - Chi nhánh TP. Hồ Chí Minh' },
  '970434': { shortName: 'IndovinaBank', name: 'Ngân hàng TNHH Indovina' },
  '970410': { shortName: 'StandardChartered', name: 'Ngân hàng TNHH MTV Standard Chartered Bank Việt Nam' }
};
